[package]
name = "fuse_client_for_fs"
version = "0.1.0"
edition = "2024"



[dependencies]
libc = "0.2"
chrono = { version = "0.4.31", features = ["clock", "std"] }
redox-scheme = "0.8.2"
bytemuck = { version = "1", features = ["derive"] }

[features]
virtio-fs = []
